use crate::emit::{
    WatEmitter, HEAP_AUX_OFFSET, HEAP_FLAGS_OFFSET, HEAP_KIND_SHIFT, HEAP_KIND_STRING,
    HEAP_LEN_OFFSET, STRING_HEADER_SIZE, TRAP_JSON_PARSE, TRAP_KIND_STRING, TRAP_NULL_DEREF,
};

pub(super) fn emit_json_decode(emitter: &mut WatEmitter) {
    emitter
        .push_line("(func $bd_json_trim_range (param $data i32) (param $len i32) (result i32 i32)");
    emitter.indent();
    emitter.push_line("(local $start i32)");
    emitter.push_line("(local $end i32)");
    emitter.push_line("(local $ch i32)");
    emitter.push_line("i32.const 0");
    emitter.push_line("local.set $start");
    emitter.push_line("local.get $len");
    emitter.push_line("local.set $end");

    let trim_start_exit = "json_trim_start_exit";
    let trim_start_loop = "json_trim_start_loop";
    emitter.push_line(format!("block ${trim_start_exit}"));
    emitter.indent();
    emitter.push_line(format!("loop ${trim_start_loop}"));
    emitter.indent();
    emitter.push_line("local.get $start");
    emitter.push_line("local.get $end");
    emitter.push_line("i32.ge_u");
    emitter.push_line(format!("br_if ${trim_start_exit}"));
    emitter.push_line("local.get $data");
    emitter.push_line("local.get $start");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load8_u");
    emitter.push_line("local.set $ch");
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 32");
    emitter.push_line("i32.eq");
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 10");
    emitter.push_line("i32.eq");
    emitter.push_line("i32.or");
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 13");
    emitter.push_line("i32.eq");
    emitter.push_line("i32.or");
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 9");
    emitter.push_line("i32.eq");
    emitter.push_line("i32.or");
    emitter.push_line("i32.eqz");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("br ${trim_start_exit}"));
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $start");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("local.set $start");
    emitter.push_line(format!("br ${trim_start_loop}"));
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");

    let trim_end_exit = "json_trim_end_exit";
    let trim_end_loop = "json_trim_end_loop";
    emitter.push_line(format!("block ${trim_end_exit}"));
    emitter.indent();
    emitter.push_line(format!("loop ${trim_end_loop}"));
    emitter.indent();
    emitter.push_line("local.get $end");
    emitter.push_line("local.get $start");
    emitter.push_line("i32.le_u");
    emitter.push_line(format!("br_if ${trim_end_exit}"));
    emitter.push_line("local.get $data");
    emitter.push_line("local.get $end");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.sub");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load8_u");
    emitter.push_line("local.set $ch");
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 32");
    emitter.push_line("i32.eq");
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 10");
    emitter.push_line("i32.eq");
    emitter.push_line("i32.or");
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 13");
    emitter.push_line("i32.eq");
    emitter.push_line("i32.or");
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 9");
    emitter.push_line("i32.eq");
    emitter.push_line("i32.or");
    emitter.push_line("i32.eqz");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("br ${trim_end_exit}"));
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $end");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.sub");
    emitter.push_line("local.set $end");
    emitter.push_line(format!("br ${trim_end_loop}"));
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $start");
    emitter.push_line("local.get $end");
    emitter.dedent();
    emitter.push_line(")");

    emitter.push_line("(func $bd_json_decode_i64 (param $ptr i32) (result i64)");
    emitter.indent();
    emitter.push_line("(local $len i32)");
    emitter.push_line("(local $idx i32)");
    emitter.push_line("(local $start i32)");
    emitter.push_line("(local $end i32)");
    emitter.push_line("(local $sign i64)");
    emitter.push_line("(local $value i64)");
    emitter.push_line("(local $digit i64)");
    emitter.push_line("(local $ch i32)");
    emitter.push_line("(local $max_div10 i64)");
    emitter.push_line("(local $max_mod i64)");
    emitter.push_line("(local $data i32)");

    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.eqz");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_NULL_DEREF}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.load");
    emitter.push_line(format!("i32.const {HEAP_KIND_SHIFT}"));
    emitter.push_line("i32.shr_u");
    emitter.push_line(format!("i32.const {HEAP_KIND_STRING}"));
    emitter.push_line("i32.ne");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_KIND_STRING}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.load offset={HEAP_LEN_OFFSET}"));
    emitter.push_line("local.set $len");
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.const {STRING_HEADER_SIZE}"));
    emitter.push_line("i32.add");
    emitter.push_line("local.set $data");

    emitter.push_line("local.get $data");
    emitter.push_line("local.get $len");
    emitter.push_line("call $bd_json_trim_range");
    emitter.push_line("local.set $end");
    emitter.push_line("local.set $start");
    emitter.push_line("local.get $end");
    emitter.push_line("local.get $start");
    emitter.push_line("i32.sub");
    emitter.push_line("local.set $len");
    emitter.push_line("local.get $len");
    emitter.push_line("i32.eqz");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $data");
    emitter.push_line("local.get $start");
    emitter.push_line("i32.add");
    emitter.push_line("local.set $data");

    emitter.push_line("i32.const 0");
    emitter.push_line("local.set $idx");
    emitter.push_line("i64.const 1");
    emitter.push_line("local.set $sign");
    emitter.push_line("i64.const 922337203685477580");
    emitter.push_line("local.set $max_div10");
    emitter.push_line("i64.const 7");
    emitter.push_line("local.set $max_mod");

    emitter.push_line("local.get $data");
    emitter.push_line("i32.load8_u");
    emitter.push_line("local.set $ch");
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 45");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i64.const -1");
    emitter.push_line("local.set $sign");
    emitter.push_line("i64.const 8");
    emitter.push_line("local.set $max_mod");
    emitter.push_line("i32.const 1");
    emitter.push_line("local.set $idx");
    emitter.push_line("local.get $len");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("i64.const 0");
    emitter.push_line("local.set $value");

    let json_i64_exit = "json_i64_exit";
    let json_i64_loop = "json_i64_loop";
    emitter.push_line(format!("block ${json_i64_exit}"));
    emitter.indent();
    emitter.push_line(format!("loop ${json_i64_loop}"));
    emitter.indent();
    emitter.push_line("local.get $idx");
    emitter.push_line("local.get $len");
    emitter.push_line("i32.ge_u");
    emitter.push_line(format!("br_if ${json_i64_exit}"));

    emitter.push_line("local.get $data");
    emitter.push_line("local.get $idx");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load8_u");
    emitter.push_line("local.set $ch");

    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 48");
    emitter.push_line("i32.lt_u");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 57");
    emitter.push_line("i32.gt_u");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 48");
    emitter.push_line("i32.sub");
    emitter.push_line("i64.extend_i32_u");
    emitter.push_line("local.set $digit");

    emitter.push_line("local.get $value");
    emitter.push_line("local.get $max_div10");
    emitter.push_line("i64.gt_u");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $value");
    emitter.push_line("local.get $max_div10");
    emitter.push_line("i64.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("local.get $digit");
    emitter.push_line("local.get $max_mod");
    emitter.push_line("i64.gt_u");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $value");
    emitter.push_line("i64.const 10");
    emitter.push_line("i64.mul");
    emitter.push_line("local.get $digit");
    emitter.push_line("i64.add");
    emitter.push_line("local.set $value");

    emitter.push_line("local.get $idx");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("local.set $idx");
    emitter.push_line(format!("br ${json_i64_loop}"));
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $sign");
    emitter.push_line("i64.const -1");
    emitter.push_line("i64.eq");
    emitter.push_line("if (result i64)");
    emitter.indent();
    emitter.push_line("i64.const 0");
    emitter.push_line("local.get $value");
    emitter.push_line("i64.sub");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $value");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line(")");

    emitter.push_line("(func $bd_json_decode_bool (param $ptr i32) (result i32)");
    emitter.indent();
    emitter.push_line("(local $len i32)");
    emitter.push_line("(local $start i32)");
    emitter.push_line("(local $end i32)");
    emitter.push_line("(local $data i32)");

    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.eqz");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_NULL_DEREF}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.load");
    emitter.push_line(format!("i32.const {HEAP_KIND_SHIFT}"));
    emitter.push_line("i32.shr_u");
    emitter.push_line(format!("i32.const {HEAP_KIND_STRING}"));
    emitter.push_line("i32.ne");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_KIND_STRING}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.load offset={HEAP_LEN_OFFSET}"));
    emitter.push_line("local.set $len");
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.const {STRING_HEADER_SIZE}"));
    emitter.push_line("i32.add");
    emitter.push_line("local.set $data");

    emitter.push_line("local.get $data");
    emitter.push_line("local.get $len");
    emitter.push_line("call $bd_json_trim_range");
    emitter.push_line("local.set $end");
    emitter.push_line("local.set $start");
    emitter.push_line("local.get $end");
    emitter.push_line("local.get $start");
    emitter.push_line("i32.sub");
    emitter.push_line("local.set $len");
    emitter.push_line("local.get $data");
    emitter.push_line("local.get $start");
    emitter.push_line("i32.add");
    emitter.push_line("local.set $data");

    emitter.push_line("local.get $len");
    emitter.push_line("i32.const 4");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("local.get $data");
    emitter.push_line("i32.load8_u");
    emitter.push_line("i32.const 116");
    emitter.push_line("i32.ne");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $data");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load8_u");
    emitter.push_line("i32.const 114");
    emitter.push_line("i32.ne");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $data");
    emitter.push_line("i32.const 2");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load8_u");
    emitter.push_line("i32.const 117");
    emitter.push_line("i32.ne");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $data");
    emitter.push_line("i32.const 3");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load8_u");
    emitter.push_line("i32.const 101");
    emitter.push_line("i32.ne");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("i32.const 1");
    emitter.push_line("return");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $len");
    emitter.push_line("i32.const 5");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("local.get $data");
    emitter.push_line("i32.load8_u");
    emitter.push_line("i32.const 102");
    emitter.push_line("i32.ne");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $data");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load8_u");
    emitter.push_line("i32.const 97");
    emitter.push_line("i32.ne");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $data");
    emitter.push_line("i32.const 2");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load8_u");
    emitter.push_line("i32.const 108");
    emitter.push_line("i32.ne");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $data");
    emitter.push_line("i32.const 3");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load8_u");
    emitter.push_line("i32.const 115");
    emitter.push_line("i32.ne");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $data");
    emitter.push_line("i32.const 4");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load8_u");
    emitter.push_line("i32.const 101");
    emitter.push_line("i32.ne");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("i32.const 0");
    emitter.push_line("return");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.push_line("i32.const 0");
    emitter.dedent();
    emitter.push_line(")");

    emitter.push_line("(func $bd_json_decode_string (param $ptr i32) (result i32)");
    emitter.indent();
    emitter.push_line("(local $len i32)");
    emitter.push_line("(local $idx i32)");
    emitter.push_line("(local $start i32)");
    emitter.push_line("(local $end i32)");
    emitter.push_line("(local $data i32)");
    emitter.push_line("(local $out_ptr i32)");
    emitter.push_line("(local $out_data i32)");
    emitter.push_line("(local $write_idx i32)");
    emitter.push_line("(local $ch i32)");
    emitter.push_line("(local $esc i32)");

    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.eqz");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_NULL_DEREF}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.load");
    emitter.push_line(format!("i32.const {HEAP_KIND_SHIFT}"));
    emitter.push_line("i32.shr_u");
    emitter.push_line(format!("i32.const {HEAP_KIND_STRING}"));
    emitter.push_line("i32.ne");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_KIND_STRING}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.load offset={HEAP_LEN_OFFSET}"));
    emitter.push_line("local.set $len");
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.const {STRING_HEADER_SIZE}"));
    emitter.push_line("i32.add");
    emitter.push_line("local.set $data");

    emitter.push_line("local.get $data");
    emitter.push_line("local.get $len");
    emitter.push_line("call $bd_json_trim_range");
    emitter.push_line("local.set $end");
    emitter.push_line("local.set $start");
    emitter.push_line("local.get $end");
    emitter.push_line("local.get $start");
    emitter.push_line("i32.sub");
    emitter.push_line("local.set $len");
    emitter.push_line("local.get $len");
    emitter.push_line("i32.const 2");
    emitter.push_line("i32.lt_u");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $data");
    emitter.push_line("local.get $start");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load8_u");
    emitter.push_line("i32.const 34");
    emitter.push_line("i32.ne");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $data");
    emitter.push_line("local.get $end");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.sub");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load8_u");
    emitter.push_line("i32.const 34");
    emitter.push_line("i32.ne");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $start");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("local.set $start");
    emitter.push_line("local.get $end");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.sub");
    emitter.push_line("local.set $end");
    emitter.push_line("local.get $end");
    emitter.push_line("local.get $start");
    emitter.push_line("i32.sub");
    emitter.push_line("local.set $len");

    emitter.push_line("local.get $len");
    emitter.push_line(format!("i32.const {STRING_HEADER_SIZE}"));
    emitter.push_line("i32.add");
    emitter.push_line("call $bd_alloc");
    emitter.push_line("local.set $out_ptr");
    emitter.push_line("local.get $out_ptr");
    emitter.push_line(format!("i32.const {}", HEAP_KIND_STRING << HEAP_KIND_SHIFT));
    emitter.push_line("i32.store");
    emitter.push_line("local.get $out_ptr");
    emitter.push_line("i32.const 0");
    emitter.push_line(format!("i32.store offset={HEAP_FLAGS_OFFSET}"));
    emitter.push_line("local.get $out_ptr");
    emitter.push_line("i32.const 0");
    emitter.push_line(format!("i32.store offset={HEAP_AUX_OFFSET}"));
    emitter.push_line("local.get $out_ptr");
    emitter.push_line("local.get $len");
    emitter.push_line(format!("i32.store offset={HEAP_LEN_OFFSET}"));
    emitter.push_line("local.get $out_ptr");
    emitter.push_line(format!("i32.const {STRING_HEADER_SIZE}"));
    emitter.push_line("i32.add");
    emitter.push_line("local.set $out_data");
    emitter.push_line("i32.const 0");
    emitter.push_line("local.set $write_idx");
    emitter.push_line("local.get $start");
    emitter.push_line("local.set $idx");

    let dec_exit = "json_dec_exit";
    let dec_loop = "json_dec_loop";
    emitter.push_line(format!("block ${dec_exit}"));
    emitter.indent();
    emitter.push_line(format!("loop ${dec_loop}"));
    emitter.indent();
    emitter.push_line("local.get $idx");
    emitter.push_line("local.get $end");
    emitter.push_line("i32.ge_u");
    emitter.push_line(format!("br_if ${dec_exit}"));

    emitter.push_line("local.get $data");
    emitter.push_line("local.get $idx");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load8_u");
    emitter.push_line("local.set $ch");

    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 92");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("local.get $idx");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("local.set $idx");
    emitter.push_line("local.get $idx");
    emitter.push_line("local.get $end");
    emitter.push_line("i32.ge_u");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $data");
    emitter.push_line("local.get $idx");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load8_u");
    emitter.push_line("local.set $ch");

    emitter.push_line("i32.const 0");
    emitter.push_line("local.set $esc");
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 34");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 34");
    emitter.push_line("local.set $esc");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 92");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 92");
    emitter.push_line("local.set $esc");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 47");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 47");
    emitter.push_line("local.set $esc");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 98");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 8");
    emitter.push_line("local.set $esc");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 102");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 12");
    emitter.push_line("local.set $esc");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 110");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 10");
    emitter.push_line("local.set $esc");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 114");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 13");
    emitter.push_line("local.set $esc");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 116");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 9");
    emitter.push_line("local.set $esc");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $out_data");
    emitter.push_line("local.get $write_idx");
    emitter.push_line("i32.add");
    emitter.push_line("local.get $esc");
    emitter.push_line("i32.store8");
    emitter.push_line("local.get $write_idx");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("local.set $write_idx");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 32");
    emitter.push_line("i32.lt_u");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $out_data");
    emitter.push_line("local.get $write_idx");
    emitter.push_line("i32.add");
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.store8");
    emitter.push_line("local.get $write_idx");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("local.set $write_idx");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $idx");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("local.set $idx");
    emitter.push_line(format!("br ${dec_loop}"));
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $out_ptr");
    emitter.push_line("local.get $write_idx");
    emitter.push_line(format!("i32.store offset={HEAP_LEN_OFFSET}"));
    emitter.push_line("local.get $out_ptr");
    emitter.dedent();
    emitter.push_line(")");
}
