use crate::emit::{
    WatEmitter, HEAP_AUX_OFFSET, HEAP_FLAGS_OFFSET, HEAP_KIND_SHIFT, HEAP_KIND_STRING,
    HEAP_LEN_OFFSET, STRING_HEADER_SIZE, TRAP_ARRAY_OOM, TRAP_JSON_PARSE, TRAP_KIND_STRING,
    TRAP_NULL_DEREF,
};

pub(super) fn emit_json_encode(emitter: &mut WatEmitter, max_input_len: i32) {
    emitter.push_line("(func $bd_json_encode_i64 (param $value i64) (result i32)");
    emitter.indent();
    emitter.push_line("local.get $value");
    emitter.push_line("call $bd_string_from_i64");
    emitter.dedent();
    emitter.push_line(")");

    emitter.push_line("(func $bd_json_encode_bool (param $value i32) (result i32)");
    emitter.indent();
    emitter.push_line("(local $ptr i32)");
    emitter.push_line("local.get $value");
    emitter.push_line("i32.eqz");
    emitter.push_line("if (result i32)");
    emitter.indent();
    emitter.push_line(format!("i32.const {}", STRING_HEADER_SIZE + 5));
    emitter.push_line("call $bd_alloc");
    emitter.push_line("local.set $ptr");
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.const {}", HEAP_KIND_STRING << HEAP_KIND_SHIFT));
    emitter.push_line("i32.store");
    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.const 0");
    emitter.push_line(format!("i32.store offset={HEAP_FLAGS_OFFSET}"));
    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.const 0");
    emitter.push_line(format!("i32.store offset={HEAP_AUX_OFFSET}"));
    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.const 5");
    emitter.push_line(format!("i32.store offset={HEAP_LEN_OFFSET}"));
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.const {STRING_HEADER_SIZE}"));
    emitter.push_line("i32.add");
    emitter.push_line("i32.const 102");
    emitter.push_line("i32.store8");
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.const {}", STRING_HEADER_SIZE + 1));
    emitter.push_line("i32.add");
    emitter.push_line("i32.const 97");
    emitter.push_line("i32.store8");
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.const {}", STRING_HEADER_SIZE + 2));
    emitter.push_line("i32.add");
    emitter.push_line("i32.const 108");
    emitter.push_line("i32.store8");
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.const {}", STRING_HEADER_SIZE + 3));
    emitter.push_line("i32.add");
    emitter.push_line("i32.const 115");
    emitter.push_line("i32.store8");
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.const {}", STRING_HEADER_SIZE + 4));
    emitter.push_line("i32.add");
    emitter.push_line("i32.const 101");
    emitter.push_line("i32.store8");
    emitter.push_line("local.get $ptr");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line(format!("i32.const {}", STRING_HEADER_SIZE + 4));
    emitter.push_line("call $bd_alloc");
    emitter.push_line("local.set $ptr");
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.const {}", HEAP_KIND_STRING << HEAP_KIND_SHIFT));
    emitter.push_line("i32.store");
    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.const 0");
    emitter.push_line(format!("i32.store offset={HEAP_FLAGS_OFFSET}"));
    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.const 0");
    emitter.push_line(format!("i32.store offset={HEAP_AUX_OFFSET}"));
    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.const 4");
    emitter.push_line(format!("i32.store offset={HEAP_LEN_OFFSET}"));
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.const {STRING_HEADER_SIZE}"));
    emitter.push_line("i32.add");
    emitter.push_line("i32.const 116");
    emitter.push_line("i32.store8");
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.const {}", STRING_HEADER_SIZE + 1));
    emitter.push_line("i32.add");
    emitter.push_line("i32.const 114");
    emitter.push_line("i32.store8");
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.const {}", STRING_HEADER_SIZE + 2));
    emitter.push_line("i32.add");
    emitter.push_line("i32.const 117");
    emitter.push_line("i32.store8");
    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.const {}", STRING_HEADER_SIZE + 3));
    emitter.push_line("i32.add");
    emitter.push_line("i32.const 101");
    emitter.push_line("i32.store8");
    emitter.push_line("local.get $ptr");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line(")");
    emitter.push_line("(func $bd_json_encode_string (param $ptr i32) (result i32)");
    emitter.indent();
    emitter.push_line("(local $len i32)");
    emitter.push_line("(local $idx i32)");
    emitter.push_line("(local $out_len i32)");
    emitter.push_line("(local $data i32)");
    emitter.push_line("(local $out_ptr i32)");
    emitter.push_line("(local $out_data i32)");
    emitter.push_line("(local $write_idx i32)");
    emitter.push_line("(local $ch i32)");
    emitter.push_line("(local $esc_char i32)");

    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.eqz");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_NULL_DEREF}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.load");
    emitter.push_line(format!("i32.const {HEAP_KIND_SHIFT}"));
    emitter.push_line("i32.shr_u");
    emitter.push_line(format!("i32.const {HEAP_KIND_STRING}"));
    emitter.push_line("i32.ne");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_KIND_STRING}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.load offset={HEAP_LEN_OFFSET}"));
    emitter.push_line("local.set $len");
    emitter.push_line("local.get $len");
    emitter.push_line(format!("i32.const {max_input_len}"));
    emitter.push_line("i32.gt_u");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_ARRAY_OOM}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $len");
    emitter.push_line("i32.const 2");
    emitter.push_line("i32.mul");
    emitter.push_line("i32.const 2");
    emitter.push_line("i32.add");
    emitter.push_line("local.set $out_len");

    emitter.push_line("local.get $out_len");
    emitter.push_line(format!("i32.const {STRING_HEADER_SIZE}"));
    emitter.push_line("i32.add");
    emitter.push_line("call $bd_alloc");
    emitter.push_line("local.set $out_ptr");
    emitter.push_line("local.get $out_ptr");
    emitter.push_line(format!("i32.const {}", HEAP_KIND_STRING << HEAP_KIND_SHIFT));
    emitter.push_line("i32.store");
    emitter.push_line("local.get $out_ptr");
    emitter.push_line("i32.const 0");
    emitter.push_line(format!("i32.store offset={HEAP_FLAGS_OFFSET}"));
    emitter.push_line("local.get $out_ptr");
    emitter.push_line("i32.const 0");
    emitter.push_line(format!("i32.store offset={HEAP_AUX_OFFSET}"));
    emitter.push_line("local.get $out_ptr");
    emitter.push_line("local.get $out_len");
    emitter.push_line(format!("i32.store offset={HEAP_LEN_OFFSET}"));
    emitter.push_line("local.get $out_ptr");
    emitter.push_line(format!("i32.const {STRING_HEADER_SIZE}"));
    emitter.push_line("i32.add");
    emitter.push_line("local.set $out_data");

    emitter.push_line("local.get $ptr");
    emitter.push_line(format!("i32.const {STRING_HEADER_SIZE}"));
    emitter.push_line("i32.add");
    emitter.push_line("local.set $data");

    emitter.push_line("local.get $out_data");
    emitter.push_line("i32.const 34");
    emitter.push_line("i32.store8");
    emitter.push_line("i32.const 1");
    emitter.push_line("local.set $write_idx");
    emitter.push_line("i32.const 0");
    emitter.push_line("local.set $idx");

    let enc_exit = "json_enc_exit";
    let enc_loop = "json_enc_loop";
    emitter.push_line(format!("block ${enc_exit}"));
    emitter.indent();
    emitter.push_line(format!("loop ${enc_loop}"));
    emitter.indent();
    emitter.push_line("local.get $idx");
    emitter.push_line("local.get $len");
    emitter.push_line("i32.ge_u");
    emitter.push_line(format!("br_if ${enc_exit}"));

    emitter.push_line("local.get $data");
    emitter.push_line("local.get $idx");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load8_u");
    emitter.push_line("local.set $ch");

    emitter.push_line("i32.const 0");
    emitter.push_line("local.set $esc_char");
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 34");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 34");
    emitter.push_line("local.set $esc_char");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 92");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 92");
    emitter.push_line("local.set $esc_char");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 10");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 110");
    emitter.push_line("local.set $esc_char");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 13");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 114");
    emitter.push_line("local.set $esc_char");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 9");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 116");
    emitter.push_line("local.set $esc_char");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 8");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 98");
    emitter.push_line("local.set $esc_char");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 12");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 102");
    emitter.push_line("local.set $esc_char");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $esc_char");
    emitter.push_line("i32.eqz");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.const 32");
    emitter.push_line("i32.lt_u");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_JSON_PARSE}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $out_data");
    emitter.push_line("local.get $write_idx");
    emitter.push_line("i32.add");
    emitter.push_line("local.get $ch");
    emitter.push_line("i32.store8");
    emitter.push_line("local.get $write_idx");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("local.set $write_idx");
    emitter.dedent();
    emitter.push_line("else");
    emitter.indent();
    emitter.push_line("local.get $out_data");
    emitter.push_line("local.get $write_idx");
    emitter.push_line("i32.add");
    emitter.push_line("i32.const 92");
    emitter.push_line("i32.store8");
    emitter.push_line("local.get $out_data");
    emitter.push_line("local.get $write_idx");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("i32.add");
    emitter.push_line("local.get $esc_char");
    emitter.push_line("i32.store8");
    emitter.push_line("local.get $write_idx");
    emitter.push_line("i32.const 2");
    emitter.push_line("i32.add");
    emitter.push_line("local.set $write_idx");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $idx");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("local.set $idx");
    emitter.push_line(format!("br ${enc_loop}"));
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");

    emitter.push_line("local.get $out_data");
    emitter.push_line("local.get $write_idx");
    emitter.push_line("i32.add");
    emitter.push_line("i32.const 34");
    emitter.push_line("i32.store8");
    emitter.push_line("local.get $write_idx");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("local.set $write_idx");
    emitter.push_line("local.get $out_ptr");
    emitter.push_line("local.get $write_idx");
    emitter.push_line(format!("i32.store offset={HEAP_LEN_OFFSET}"));
    emitter.push_line("local.get $out_ptr");
    emitter.dedent();
    emitter.push_line(")");
}
