use crate::emit::{
    WatEmitter,
    TRAP_TRACE_OOM,
};

pub(super) fn emit_gc_worklist(emitter: &mut WatEmitter, mark_ptr_offset: i32, mark_data_offset: i32, mark_slots: i32, seen_ptr_offset: i32, seen_data_offset: i32, seen_slots: i32) {
    emitter.push_line("(func $bd_mark_clear");
    emitter.indent();
    emitter.push_line(format!("i32.const {mark_ptr_offset}"));
    emitter.push_line("i32.const 0");
    emitter.push_line("i32.store");
    emitter.push_line(format!("i32.const {seen_ptr_offset}"));
    emitter.push_line("i32.const 0");
    emitter.push_line("i32.store");
    emitter.dedent();
    emitter.push_line(")");

    emitter.push_line("(func $bd_mark_push (param $ptr i32)");
    emitter.indent();
    emitter.push_line("(local $sp i32)");
    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.eqz");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("return");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line(format!("i32.const {mark_ptr_offset}"));
    emitter.push_line("i32.load");
    emitter.push_line("local.set $sp");
    emitter.push_line("local.get $sp");
    emitter.push_line(format!("i32.const {mark_slots}"));
    emitter.push_line("i32.ge_u");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_TRACE_OOM}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line(format!("i32.const {mark_data_offset}"));
    emitter.push_line("local.get $sp");
    emitter.push_line("i32.const 4");
    emitter.push_line("i32.mul");
    emitter.push_line("i32.add");
    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.store");
    emitter.push_line(format!("i32.const {mark_ptr_offset}"));
    emitter.push_line("local.get $sp");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("i32.store");
    emitter.dedent();
    emitter.push_line(")");

    emitter.push_line("(func $bd_mark_pop (result i32)");
    emitter.indent();
    emitter.push_line("(local $sp i32)");
    emitter.push_line(format!("i32.const {mark_ptr_offset}"));
    emitter.push_line("i32.load");
    emitter.push_line("local.set $sp");
    emitter.push_line("local.get $sp");
    emitter.push_line("i32.eqz");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 0");
    emitter.push_line("return");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $sp");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.sub");
    emitter.push_line("local.set $sp");
    emitter.push_line(format!("i32.const {mark_ptr_offset}"));
    emitter.push_line("local.get $sp");
    emitter.push_line("i32.store");
    emitter.push_line(format!("i32.const {mark_data_offset}"));
    emitter.push_line("local.get $sp");
    emitter.push_line("i32.const 4");
    emitter.push_line("i32.mul");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load");
    emitter.dedent();
    emitter.push_line(")");

    emitter.push_line("(func $bd_seen_contains (param $ptr i32) (result i32)");
    emitter.indent();
    emitter.push_line("(local $idx i32)");
    emitter.push_line("(local $len i32)");
    emitter.push_line(format!("i32.const {seen_ptr_offset}"));
    emitter.push_line("i32.load");
    emitter.push_line("local.set $len");
    emitter.push_line("i32.const 0");
    emitter.push_line("local.set $idx");
    let exit_label = "seen_exit";
    let loop_label = "seen_loop";
    emitter.push_line(format!("block ${exit_label}"));
    emitter.indent();
    emitter.push_line(format!("loop ${loop_label}"));
    emitter.indent();
    emitter.push_line("local.get $idx");
    emitter.push_line("local.get $len");
    emitter.push_line("i32.ge_u");
    emitter.push_line(format!("br_if ${exit_label}"));
    emitter.push_line(format!("i32.const {seen_data_offset}"));
    emitter.push_line("local.get $idx");
    emitter.push_line("i32.const 4");
    emitter.push_line("i32.mul");
    emitter.push_line("i32.add");
    emitter.push_line("i32.load");
    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.eq");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line("i32.const 1");
    emitter.push_line("return");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("local.get $idx");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("local.set $idx");
    emitter.push_line(format!("br ${loop_label}"));
    emitter.dedent();
    emitter.push_line("end");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line("i32.const 0");
    emitter.dedent();
    emitter.push_line(")");

    emitter.push_line("(func $bd_seen_add (param $ptr i32)");
    emitter.indent();
    emitter.push_line("(local $len i32)");
    emitter.push_line(format!("i32.const {seen_ptr_offset}"));
    emitter.push_line("i32.load");
    emitter.push_line("local.set $len");
    emitter.push_line("local.get $len");
    emitter.push_line(format!("i32.const {seen_slots}"));
    emitter.push_line("i32.ge_u");
    emitter.push_line("if");
    emitter.indent();
    emitter.push_line(format!("i32.const {TRAP_TRACE_OOM}"));
    emitter.push_line("call $bd_trap");
    emitter.dedent();
    emitter.push_line("end");
    emitter.push_line(format!("i32.const {seen_data_offset}"));
    emitter.push_line("local.get $len");
    emitter.push_line("i32.const 4");
    emitter.push_line("i32.mul");
    emitter.push_line("i32.add");
    emitter.push_line("local.get $ptr");
    emitter.push_line("i32.store");
    emitter.push_line(format!("i32.const {seen_ptr_offset}"));
    emitter.push_line("local.get $len");
    emitter.push_line("i32.const 1");
    emitter.push_line("i32.add");
    emitter.push_line("i32.store");
    emitter.dedent();
    emitter.push_line(")");

}
